version: '3.8'

services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # MySQL 루트 비밀번호
      MYSQL_DATABASE: pilot-01         # 기본으로 생성할 데이터베이스
      MYSQL_USER: user                 # MySQL 사용자 이름
      MYSQL_PASSWORD: 1234     # 사용자 비밀번호
    ports:
      - "3306:3306"                    # 로컬 포트와 컨테이너 포트 매핑
    volumes:
      - mysql_data:/var/lib/mysql      # 데이터 영구 저장

volumes:
  mysql_data:
